import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";

import { Chrome, Gauge } from "@/components/pepys/Chrome";
import { CorpusPanel } from "@/components/pepys/CorpusPanel";
import { CUTOFF_OPTIONS, cutoffLabel } from "@/lib/firewall";
import { pct } from "@/lib/pepys";
import { setRevealStatus } from "@/lib/pepys.functions";
import { rebuildPersonality, setCutoff } from "@/lib/research.functions";
import { curiosityQuery, dossierQuery, instrumentationQuery } from "@/lib/queries";


export const Route = createFileRoute("/research")({
  head: () => ({
    meta: [
      { title: "Research Mode — PEPYS reconstruction instrumentation" },
      {
        name: "description",
        content:
          "State transitions, evidence tiers, knowledge-frontier integrity and the identity reveal condition for the Samuel Pepys reconstruction.",
      },
      { property: "og:title", content: "Research Mode — PEPYS" },
      {
        property: "og:description",
        content:
          "Auditable state transitions and experimental conditions behind the Pepys reconstruction.",
      },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
  component: ResearchMode,
});

function ResearchMode() {
  const queryClient = useQueryClient();
  const { data } = useQuery(dossierQuery);
  const curiosity = useQuery(curiosityQuery);
  const instrumentation = useQuery(instrumentationQuery);
  const runReveal = useServerFn(setRevealStatus);
  const runSetCutoff = useServerFn(setCutoff);
  const runPersonality = useServerFn(rebuildPersonality);

  const reveal = useMutation({
    mutationFn: (revealed: boolean) => runReveal({ data: { revealed } }),
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: ["dossier"] });
      void queryClient.invalidateQueries({ queryKey: ["instrumentation"] });
    },
  });

  const cutoffMutation = useMutation({
    mutationFn: (option: { cutoff: string; label: string }) => runSetCutoff({ data: option }),
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: ["instrumentation"] });
      void queryClient.invalidateQueries({ queryKey: ["dossier"] });
    },
  });

  const personalityMutation = useMutation({
    mutationFn: () => runPersonality({}),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["instrumentation"] }),
  });

  const instr = instrumentation.data;
  const activeCutoff = instr?.state?.historical_cutoff ?? "1669-05-31";


  const unknown = data?.concepts.filter((c) => c.status === "unknown") ?? [];
  const partial = data?.concepts.filter((c) => c.status === "partial") ?? [];
  const understood = data?.concepts.filter((c) => c.status === "understood") ?? [];
  const learnedMemories = data?.memories.filter((m) => m.scope !== "original") ?? [];
  const learnedBeliefs = data?.beliefs.filter((b) => b.origin === "learned") ?? [];
  const revealed = data?.subject.reveal_status === "revealed";
  const total = data?.concepts.length ?? 0;
  const questions = curiosity.data?.questions ?? [];
  const asked = questions.filter((q) => q.asked);
  const answered = questions.filter((q) => q.answered);
  const recursive = questions.filter((q) => q.depth > 1);

  const metrics = [
    { label: "Registered sources", value: String(data?.sources.length ?? 0), note: "tiered corpus" },
    {
      label: "Frontier integrity",
      value: total ? pct(unknown.length / total) : "—",
      note: "share of modern concepts still unknown",
    },
    {
      label: "Post-reconstruction memories",
      value: String(learnedMemories.length),
      note: "tagged separately from original life",
    },
    { label: "Belief revisions", value: String(learnedBeliefs.length), note: "provenance recorded" },
    { label: "Logged transitions", value: String(data?.log.length ?? 0), note: "auditable events" },
    { label: "Turns exchanged", value: String(data?.messageCount ?? 0), note: "across all visitors" },
    {
      label: "Active curiosities",
      value: String((curiosity.data?.states ?? []).filter((c) => !c.resolved).length),
      note: "unresolved, scored from his own evidence",
    },
    {
      label: "Questions he asked",
      value: `${asked.length} asked / ${answered.length} answered`,
      note: "generated by state, not scripted",
    },
    {
      label: "Recursive follow-ups",
      value: String(recursive.length),
      note: "questions arising from answers to his own questions",
    },
    {
      label: "Firewall denials",
      value: String(instr?.denials.length ?? 0),
      note: "retrievals refused for falling after the cutoff",
    },
    {
      label: "Leakage events",
      value: String(instr?.leaks.length ?? 0),
      note: "post-cutoff vocabulary caught in output",
    },
    {
      label: "Provenance records",
      value: String(instr?.counts.provenance ?? 0),
      note: "memories with a traceable origin",
    },
    {
      label: "Visitors known",
      value: String(instr?.counts.visitors ?? 0),
      note: "separate relationships, memory kept private per visitor",
    },
  ];

  const subsystems = [
    {
      label: "Corpus ingestion (verbatim diary)",
      backing: "diary_entries, segmented by date from the Wheatley edition",
      count: instr?.counts.entries ?? 0,
    },
    {
      label: "Hybrid retrieval (lexical + semantic)",
      backing: "diary_chunks embeddings fused with ts_rank, cutoff-bound in SQL",
      count: instr?.counts.entries ?? 0,
    },
    {
      label: "Historical access firewall",
      backing: "access_denials rows written whenever a later entry is refused",
      count: instr?.denials.length ?? 0,
    },
    {
      label: "Leakage detection",
      backing: "leakage_events from post-cutoff vocabulary scanned in output",
      count: instr?.leaks.length ?? 0,
    },
    {
      label: "Belief revision history",
      backing: "belief_history rows with confidence and stance before/after",
      count: instr?.revisions.length ?? 0,
    },
    {
      label: "Contradiction recording",
      backing: "contradictions raised instead of overwriting a held belief",
      count: instr?.contradictions.length ?? 0,
    },
    {
      label: "Memory provenance",
      backing: "provenance_records tying each memory to its interaction",
      count: instr?.counts.provenance ?? 0,
    },
    {
      label: "Personality derivation",
      backing: "personality_traits scored from his own records",
      count: instr?.traits.length ?? 0,
    },
    {
      label: "Curiosity engine",
      backing: "curiosity_states and generated questions, ranked in code",
      count: (curiosity.data?.states ?? []).length,
    },
    {
      label: "Per-visitor relationships and private memory",
      backing: "relationships rows, memory scoped to its owner",
      count: instr?.counts.visitors ?? 0,
    },
  ];


  return (
    <Chrome subtitle="Research Mode">
      <main className="mx-auto max-w-6xl space-y-8 px-5 py-10">
        <header className="space-y-2">
          <p className="small-caps-label">Instrumentation</p>
          <h1 className="font-display text-3xl">Reconstruction state and experiments</h1>
          <p className="max-w-2xl text-sm text-muted-foreground">
            Every conclusion the agent reaches is recorded as a state transition with its evidence,
            so a run can be inspected and reproduced. Nothing here is visible to the agent.
          </p>
        </header>

        <section className="leaf space-y-4 p-5">
          <div>
            <p className="small-caps-label">Build status</p>
            <h2 className="font-display text-2xl">V4 cognitive engine — implemented</h2>
            <p className="mt-1 max-w-2xl text-sm text-muted-foreground">
              Each subsystem below is backed by database rows, not prompt wording. &ldquo;Live&rdquo;
              means the subsystem is wired and has written records; &ldquo;Wired, no records
              yet&rdquo; means the code path exists but nothing has triggered it in this run.
            </p>
          </div>
          <div className="grid gap-2 sm:grid-cols-2">
            {subsystems.map((s) => (
              <div
                key={s.label}
                className="flex items-start justify-between gap-3 rounded-md border border-border/70 p-3"
              >
                <div>
                  <p className="text-sm">{s.label}</p>
                  <p className="text-xs text-muted-foreground">{s.backing}</p>
                </div>
                <span
                  className={`whitespace-nowrap rounded-sm px-2 py-0.5 font-mono text-[10px] ${
                    s.count > 0
                      ? "bg-seal text-seal-foreground"
                      : "border border-border text-muted-foreground"
                  }`}
                >
                  {s.count > 0 ? `live · ${s.count}` : "wired · 0"}
                </span>
              </div>
            ))}
          </div>
        </section>

        <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">

          {metrics.map((metric) => (
            <div key={metric.label} className="leaf p-4">
              <p className="small-caps-label">{metric.label}</p>
              <p className="font-display text-3xl">{metric.value}</p>
              <p className="text-xs text-muted-foreground">{metric.note}</p>
            </div>
          ))}
        </section>

        <section className="leaf space-y-4 p-5">
          <div>
            <p className="small-caps-label">Experimental condition</p>
            <h2 className="font-display text-2xl">Historical access controller</h2>
            <p className="mt-1 text-sm text-muted-foreground">
              The cutoff is enforced in the data layer: diary entries, life events and memories dated
              after it are never retrieved, so they cannot reach the model at all. Moving the cutoff
              re-runs the whole reconstruction against a smaller life.
            </p>
          </div>
          <div className="flex flex-wrap gap-2">
            {CUTOFF_OPTIONS.map((option) => {
              const active = option.cutoff === activeCutoff;
              return (
                <button
                  key={option.cutoff}
                  type="button"
                  disabled={cutoffMutation.isPending}
                  onClick={() =>
                    cutoffMutation.mutate({ cutoff: option.cutoff, label: option.label })
                  }
                  className={`rounded-md border px-3 py-2 text-xs transition ${
                    active
                      ? "border-accent bg-accent/15 text-foreground"
                      : "border-border text-muted-foreground hover:border-accent/60"
                  }`}
                >
                  <span className="block font-display text-sm">{option.label}</span>
                  <span className="block">{option.cutoff}</span>
                </button>
              );
            })}
          </div>
          <p className="text-xs text-muted-foreground">
            Active cutoff: <span className="text-foreground">{cutoffLabel(activeCutoff)}</span>
            {instr?.state?.identity_state ? ` · identity state: ${instr.state.identity_state}` : ""}
          </p>
          {instr?.denials.length ? (
            <ul className="space-y-2 text-xs">
              {instr.denials.slice(0, 8).map((denial) => (
                <li key={denial.id} className="rounded-md border border-border bg-secondary/50 p-3">
                  <p className="text-foreground">“{denial.requested}”</p>
                  <p className="text-muted-foreground">
                    {denial.blocked_count} entr{denial.blocked_count === 1 ? "y" : "ies"} withheld ·{" "}
                    {denial.reason}
                  </p>
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-xs text-muted-foreground">
              No denials logged yet. Ask him about something from after the cutoff to exercise the
              firewall.
            </p>
          )}
        </section>

        <section className="grid gap-6 lg:grid-cols-2">
          <div className="leaf space-y-3 p-5">
            <div>
              <p className="small-caps-label">Validation</p>
              <h2 className="font-display text-2xl">Leakage detection</h2>
              <p className="mt-1 text-sm text-muted-foreground">
                Each reply is scanned for vocabulary coined after the cutoff. A term is allowed only
                if the visitor introduced it or it was taught as a concept; anything else is logged.
              </p>
            </div>
            {instr?.leaks.length ? (
              <ul className="space-y-2 text-xs">
                {instr.leaks.slice(0, 8).map((leak) => (
                  <li key={leak.id} className="rounded-md border border-border bg-secondary/50 p-3">
                    <p className="text-foreground">
                      {leak.detected_concept}{" "}
                      <span className="text-muted-foreground">({leak.severity})</span>
                    </p>
                    <p className="text-muted-foreground">…{leak.response}…</p>
                  </li>
                ))}
              </ul>
            ) : (
              <p className="rounded-md border border-border bg-secondary/50 p-3 text-xs text-muted-foreground">
                No leakage detected across the logged replies.
              </p>
            )}
          </div>

          <div className="leaf space-y-3 p-5">
            <div className="flex items-start justify-between gap-3">
              <div>
                <p className="small-caps-label">Derived state</p>
                <h2 className="font-display text-2xl">Personality profile</h2>
                <p className="mt-1 text-sm text-muted-foreground">
                  Traits are computed from markers in his own diary and records within the active
                  cutoff — not asserted in a prompt.
                </p>
              </div>
              <button
                type="button"
                className="button-quill shrink-0"
                disabled={personalityMutation.isPending}
                onClick={() => personalityMutation.mutate()}
              >
                {personalityMutation.isPending ? "Deriving…" : "Rebuild"}
              </button>
            </div>
            {instr?.traits.length ? (
              <div className="space-y-2">
                {instr.traits.map((trait) => (
                  <div key={trait.id}>
                    <Gauge label={trait.trait} value={trait.value} />
                    {trait.evidence_note ? (
                      <p className="text-xs text-muted-foreground">{trait.evidence_note}</p>
                    ) : null}
                  </div>
                ))}
              </div>
            ) : (
              <p className="rounded-md border border-border bg-secondary/50 p-3 text-xs text-muted-foreground">
                No profile derived yet. Rebuild to compute traits from the corpus.
              </p>
            )}
            {instr?.emotion ? (
              <p className="text-xs text-muted-foreground">
                Last emotional state:{" "}
                {Object.entries(instr.emotion.dimensions ?? {})
                  .map(([key, value]) => `${key} ${pct(Number(value) || 0)}`)
                  .join(" · ")}
              </p>
            ) : null}
          </div>
        </section>

        <section className="grid gap-6 lg:grid-cols-2">
          <div className="leaf space-y-3 p-5">
            <div>
              <p className="small-caps-label">Audit</p>
              <h2 className="font-display text-2xl">Belief revision history</h2>
            </div>
            {instr?.revisions.length ? (
              <ul className="space-y-2 text-xs">
                {instr.revisions.slice(0, 10).map((revision) => (
                  <li
                    key={revision.id}
                    className="rounded-md border border-border bg-secondary/50 p-3"
                  >
                    <p className="text-foreground">
                      {revision.beliefs?.proposition ?? "(belief removed)"}
                    </p>
                    <p className="text-muted-foreground">
                      {revision.stance_before ?? "not held"} (
                      {revision.confidence_before === null
                        ? "—"
                        : pct(revision.confidence_before)}) → {revision.stance_after} (
                      {pct(revision.confidence_after)}) · {revision.change_reason}
                    </p>
                  </li>
                ))}
              </ul>
            ) : (
              <p className="rounded-md border border-border bg-secondary/50 p-3 text-xs text-muted-foreground">
                No belief revisions recorded yet.
              </p>
            )}
          </div>

          <div className="leaf space-y-3 p-5">
            <div>
              <p className="small-caps-label">Audit</p>
              <h2 className="font-display text-2xl">Contradictions</h2>
              <p className="mt-1 text-sm text-muted-foreground">
                Where new testimony collided with something he already held, and how it resolved.
              </p>
            </div>
            {instr?.contradictions.length ? (
              <ul className="space-y-2 text-xs">
                {instr.contradictions.slice(0, 10).map((row) => (
                  <li key={row.id} className="rounded-md border border-border bg-secondary/50 p-3">
                    <p className="text-foreground">{row.held_proposition}</p>
                    <p className="text-muted-foreground">
                      versus “{row.new_claim}” · strength {pct(row.strength)} · {row.status}
                    </p>
                    {row.resolution ? (
                      <p className="text-muted-foreground">{row.resolution}</p>
                    ) : null}
                  </li>
                ))}
              </ul>
            ) : (
              <p className="rounded-md border border-border bg-secondary/50 p-3 text-xs text-muted-foreground">
                No contradictions logged yet.
              </p>
            )}
          </div>
        </section>

        <CorpusPanel />


        <section className="grid gap-6 lg:grid-cols-2">
          <div className="leaf space-y-4 p-5">
            <div>
              <p className="small-caps-label">Experimental condition</p>
              <h2 className="font-display text-2xl">Identity reveal</h2>
              <p className="mt-1 text-sm text-muted-foreground">
                By default the agent does not know it is a reconstruction; that fact lives only in
                protected system metadata. Activating the reveal condition tells it, and logs the
                transition so its subsequent behaviour can be compared against the concealed run.
              </p>
            </div>
            <div className="flex items-center justify-between gap-4 rounded-md border border-border bg-secondary/60 px-4 py-3">
              <div>
                <p className="text-sm font-medium">
                  {revealed ? "He has been told" : "He has not been told"}
                </p>
                <p className="font-mono text-[11px] text-muted-foreground">
                  reveal_status = {data?.subject.reveal_status ?? "hidden"}
                </p>
              </div>
              <button
                onClick={() => reveal.mutate(!revealed)}
                disabled={reveal.isPending}
                className="rounded-md bg-seal px-3 py-2 text-sm text-seal-foreground transition-opacity hover:opacity-90 disabled:opacity-50"
              >
                {reveal.isPending ? "Applying…" : revealed ? "Withdraw reveal" : "Reveal to him"}
              </button>
            </div>
          </div>

          <div className="leaf space-y-4 p-5">
            <p className="small-caps-label">Knowledge frontier integrity</p>
            <h2 className="font-display text-2xl">Future-leakage surface</h2>
            <div className="space-y-3">
              {[
                { label: "Wholly unknown", items: unknown },
                { label: "Partially understood", items: partial },
                { label: "Understood", items: understood },
              ].map((group) => (
                <div key={group.label} className="space-y-1.5">
                  <div className="flex items-center justify-between text-sm">
                    <span>{group.label}</span>
                    <span className="font-mono text-xs text-muted-foreground">
                      {group.items.length}
                    </span>
                  </div>
                  <Gauge
                    value={total ? group.items.length / total : 0}
                    label={total ? pct(group.items.length / total) : "0%"}
                  />
                </div>
              ))}
            </div>
            <p className="text-xs text-muted-foreground">
              A concept only leaves the unknown column when a visitor explains it and the
              consolidation stage records who did so.
            </p>
          </div>
        </section>

        <section className="leaf p-5">
          <p className="small-caps-label">State transition log</p>
          <h2 className="font-display text-2xl">Most recent first</h2>
          <div className="mt-4 overflow-x-auto">
            <table className="w-full min-w-[720px] text-left text-sm">
              <thead>
                <tr className="border-b border-border">
                  <th className="small-caps-label py-2">When</th>
                  <th className="small-caps-label py-2">Kind</th>
                  <th className="small-caps-label py-2">Summary</th>
                  <th className="small-caps-label py-2">Before → after</th>
                </tr>
              </thead>
              <tbody>
                {data?.log.map((entry) => (
                  <tr key={entry.id} className="border-b border-border/60 align-top">
                    <td className="py-2 pr-3 font-mono text-[11px] text-muted-foreground">
                      {new Date(entry.created_at).toLocaleString()}
                    </td>
                    <td className="py-2 pr-3">
                      <span className="rounded-full border border-border px-2 py-0.5 font-mono text-[11px]">
                        {entry.kind}
                      </span>
                    </td>
                    <td className="py-2 pr-3">{entry.summary}</td>
                    <td className="py-2 text-muted-foreground">
                      {entry.state_before} → {entry.state_after}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
            {!data?.log.length && (
              <p className="py-4 text-sm text-muted-foreground">No transitions recorded yet.</p>
            )}
          </div>
        </section>

        <section className="leaf p-5">
          <p className="small-caps-label">Evidence hierarchy</p>
          <h2 className="font-display text-2xl">Corpus by tier</h2>
          <ul className="mt-4 space-y-3">
            {data?.sources.map((source) => (
              <li key={source.id} className="flex flex-wrap items-baseline justify-between gap-2">
                <div>
                  <p className="font-display text-lg leading-snug">{source.title}</p>
                  <p className="font-mono text-[11px] text-muted-foreground">
                    {source.kind} · {source.licence}
                    {source.url ? ` · ${source.url}` : ""}
                  </p>
                </div>
                <span className="rounded-full bg-secondary px-2.5 py-1 font-mono text-[11px]">
                  tier {source.tier}
                </span>
              </li>
            ))}
          </ul>
        </section>
      </main>
    </Chrome>
  );
}
